name: CI
on:
  #pull_request:
    #branches: [develop, main]
  push:
    #branches: [feature/**, develop]
    branches: [develop, main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8 black

      - name: Lint (flake8)
        run: flake8 . --max-line-length=100

      - name: Format check (black)
        run: black --check .

      - name: Smoke tests
        run: pytest -q

      - name: Upload enriched.csv (if present)
        if: ${{ hashFiles('outputs/enriched.csv') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: enriched-csv
          path: outputs/enriched.csv
