name: CI
on:
  push:
    branches: [develop, feature/**]
  pull_request:
    branches: [develop, main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8 black

      - name: Lint check (flake8)
        run: flake8 . --max-line-length=100

      - name: Code format check (black)
        run: black --check .

      - name: Smoke tests
        run: pytest -q
